// @ts-check
// Every user-visible text of the desktop shell (tray, balloon, menus, dialogs) in each supported language.
// The panel's own UI is translated separately under public/. Keys must match across languages
// (test/electron.test.mjs checks it). Placeholders use {name}.
export const STRINGS = Object.freeze({
  en: Object.freeze({
    trayTooltip: 'SiberSentez',
    trayOpen: 'Open',
    trayOpenHub: 'Open hub folder',
    trayStartAtLogin: 'Start at login',
    trayQuit: 'Quit',
    termQuitTitle: 'Quit SiberSentez',
    termQuitMessage: '{count} terminal(s) are still running in SiberSentez.',
    termQuitDetail: 'Quitting closes them, and whatever runs in them stops.',
    termQuitYes: 'Quit and close them',
    termQuitNo: 'Cancel',
    trayHintTitle: 'SiberSentez is still running',
    trayHintBody: 'Click the tray icon to open the panel. To quit completely, right-click the icon and choose Quit.',
    menuApp: 'SiberSentez',
    menuHideWindow: 'Hide window',
    menuQuit: 'Quit',
    menuView: 'View',
    menuReload: 'Reload',
    menuActualSize: 'Actual size',
    menuZoomIn: 'Zoom in',
    menuZoomOut: 'Zoom out',
    menuFullScreen: 'Full screen',
    menuDevTools: 'Developer tools',
    errorTitle: 'SiberSentez could not start',
    errorServer: 'The panel server could not be started. Details are in the log folder:\n{logDir}',
    errorStartup: 'Startup failed: {message}',
    hubOverlapTitle: 'Hub folder is inside the program folder',
    hubOverlapBody: 'The hub folder {hub} overlaps the program folder {app}. Uninstalling SiberSentez would delete it, so it was not prepared. Choose a hub folder outside the program folder.',
    trayActions: 'Actions',
    trayActionsOff: 'Off',
    trayActionsDry: 'Preview: commands are only shown',
    trayActionsLive: 'On',
    actionsConfirmTitle: 'Turn actions on?',
    actionsConfirmBody: "With actions on, the panel's right-click menu really acts on this computer: it opens a terminal in the project folder (you start the AI tool you want there), resumes Claude Code sessions, opens folders in Explorer and in VS Code, and installs skills and agents into project folders. Choose Preview instead to only see the commands.",
    actionsConfirmBody_unix: "With actions on, the panel's right-click menu really acts on this computer: it opens a terminal in the project folder (you start the AI tool you want there), resumes Claude Code sessions, opens folders in the file manager and in VS Code, and installs skills and agents into project folders. Choose Preview instead to only see the commands.",
    actionsConfirmOk: 'Turn on',
    actionsConfirmCancel: 'Cancel',
    actionsErrorTitle: 'Actions setting not changed',
    actionsErrorNoHub: 'The hub folder is not available, so the setting could not be saved. The actions mode stays as it was.',
    actionsErrorInvalid: 'The hub settings file {file} is not valid JSON, so it was not overwritten. Fix or delete it, then try again. The actions mode stays as it was.',
    actionsErrorRead: 'The hub settings file {file} could not be read ({code}). The actions mode stays as it was.',
    actionsErrorWrite: 'The hub settings file {file} could not be saved ({code}). The actions mode stays as it was.',
    actionsUnexpectedTitle: 'Actions are on',
    actionsUnexpectedBody: "Actions are on, but they were not switched on in this app: the hub settings file {file} was changed outside SiberSentez. With actions on, the panel's right-click menu really acts on this computer. If you did not do this, choose Off: click the Actions indicator at the top of the window, or use Actions in the window menu (Alt) or in the tray menu.",
    actionsUnexpectedOk: 'OK',
    trayNewProject: 'New project…',
    newProjectPickTitle: 'Choose or create the folder of your project',
    newProjectPickButton: 'Use this folder',
    newProjectWhereTitle: 'Choose where the new project’s folder goes',
    newProjectWhereButton: 'Create it here',
    libraryPickTitle: 'Choose the folder that holds your skills or agents',
    libraryPickButton: 'Scan this folder',
    newProjectNotReadyTitle: 'SiberSentez is getting ready',
    newProjectNotReadyBody: 'SiberSentez is getting ready. Try again in a few seconds.',
  }),
  tr: Object.freeze({
    trayTooltip: 'SiberSentez',
    trayOpen: 'Aç',
    trayOpenHub: 'Merkez klasörünü aç',
    trayStartAtLogin: 'Açılışta başlat',
    trayQuit: 'Çık',
    termQuitTitle: 'SiberSentez’den çık',
    termQuitMessage: 'SiberSentez’de {count} terminal hâlâ çalışıyor.',
    termQuitDetail: 'Çıkınca kapanırlar; içlerinde çalışan her şey durur.',
    termQuitYes: 'Çık ve kapat',
    termQuitNo: 'Vazgeç',
    trayHintTitle: 'SiberSentez arka planda çalışıyor',
    trayHintBody: "SiberSentez’i açmak için tepsideki simgeye tıkla. Tamamen kapatmak için simgeye sağ tıklayıp Çık’ı seç.",
    menuApp: 'SiberSentez',
    menuHideWindow: 'Pencereyi gizle',
    menuQuit: 'Çık',
    menuView: 'Görünüm',
    menuReload: 'Yenile',
    menuActualSize: 'Gerçek boyut',
    menuZoomIn: 'Yakınlaştır',
    menuZoomOut: 'Uzaklaştır',
    menuFullScreen: 'Tam ekran',
    menuDevTools: 'Geliştirici araçları',
    errorTitle: 'SiberSentez başlatılamadı',
    errorServer: 'SiberSentez’in sunucusu başlatılamadı. Ayrıntılar kayıt klasöründe:\n{logDir}',
    errorStartup: 'Başlatma hatası: {message}',
    hubOverlapTitle: 'Merkez klasör, program klasörünün içinde',
    hubOverlapBody: 'Merkez klasör {hub}, program klasörü {app} ile iç içe. SiberSentez kaldırılınca silinirdi, bu yüzden hazırlanmadı. Program klasörünün dışında bir merkez klasör seç.',
    trayActions: 'Eylemler',
    trayActionsOff: 'Kapalı',
    trayActionsDry: 'Önizleme: komutlar yalnız gösterilir',
    trayActionsLive: 'Açık',
    actionsConfirmTitle: 'Eylemler açılsın mı?',
    actionsConfirmBody: 'Eylemler açıkken SiberSentez’in sağ tık menüsü bu bilgisayarda gerçekten iş yapar: proje klasöründe terminal açar (istediğin yapay zekâ aracını orada başlatırsın), Claude Code oturumuna devam eder, klasörleri Gezgin’de ve VS Code’da açar, skill ve ajanları proje klasörlerine kurar. Yalnız komutları görmek için bunun yerine Önizleme’yi seç.',
    actionsConfirmBody_unix: 'Eylemler açıkken SiberSentez’in sağ tık menüsü bu bilgisayarda gerçekten iş yapar: proje klasöründe terminal açar (istediğin yapay zekâ aracını orada başlatırsın), Claude Code oturumuna devam eder, klasörleri dosya yöneticisinde ve VS Code’da açar, skill ve ajanları proje klasörlerine kurar. Yalnız komutları görmek için bunun yerine Önizleme’yi seç.',
    actionsConfirmOk: 'Aç',
    actionsConfirmCancel: 'Vazgeç',
    actionsErrorTitle: 'Eylem ayarı değiştirilmedi',
    actionsErrorNoHub: 'Merkez klasör kullanılamıyor, bu yüzden ayar kaydedilemedi. Eylem kipi olduğu gibi kaldı.',
    actionsErrorInvalid: 'Merkez ayar dosyası {file} geçerli JSON değil, bu yüzden üzerine yazılmadı. Dosyayı düzelt ya da sil, sonra yeniden dene. Eylem kipi olduğu gibi kaldı.',
    actionsErrorRead: 'Merkez ayar dosyası {file} okunamadı ({code}). Eylem kipi olduğu gibi kaldı.',
    actionsErrorWrite: 'Merkez ayar dosyası {file} kaydedilemedi ({code}). Eylem kipi olduğu gibi kaldı.',
    actionsUnexpectedTitle: 'Eylemler açık',
    actionsUnexpectedBody: "Eylemler açık, ama bu uygulamadan açılmadılar: merkez ayar dosyası {file} SiberSentez dışında değiştirildi. Eylemler açıkken SiberSentez’in sağ tık menüsü bu bilgisayarda gerçekten iş yapar. Bunu sen yapmadıysan Kapalı’yı seç: üst çubuktaki Eylemler göstergesine tıkla ya da pencere menüsündeki (Alt) veya tepsi menüsündeki Eylemler’i kullan.",
    actionsUnexpectedOk: 'Tamam',
    trayNewProject: 'Yeni proje…',
    newProjectPickTitle: 'Projenin klasörünü seç ya da oluştur',
    newProjectPickButton: 'Bu klasörü kullan',
    newProjectWhereTitle: 'Yeni projenin klasörünün nereye açılacağını seç',
    newProjectWhereButton: 'Burada oluştur',
    libraryPickTitle: 'Skill ya da ajanlarının bulunduğu klasörü seç',
    libraryPickButton: 'Bu klasörü tara',
    newProjectNotReadyTitle: 'SiberSentez hazırlanıyor',
    newProjectNotReadyBody: 'SiberSentez hazırlanıyor, birkaç saniye sonra yeniden dene.',
  }),
});

// Strings for a language; unknown languages fall back to English
export function getStrings(lang) {
  return STRINGS[lang] || STRINGS.en;
}

// Fills {name} placeholders; unknown placeholders are left as they are
export function formatString(template, values = {}) {
  return String(template).replace(/\{(\w+)\}/g, (m, key) => (Object.hasOwn(values, key) ? String(values[key]) : m));
}
